(******************************************************************************)
(*                                                                            *)
(*                 Rongorongo: Rapa Nui Script Structural Logic               *)
(*                                                                            *)
(*     Formalizes rongorongo tablet corpus: reverse boustrophedon reading     *)
(*     direction (alternating lines rotated 180°), Barthel glyph inventory    *)
(*     (~120 basic signs), 26 surviving kohau artifacts. Proves structural    *)
(*     constraints any decipherment must satisfy; glyph sequence patterns.    *)
(*                                                                            *)
(*     "The small remnant of the natives have not the remotest idea of the    *)
(*     meaning of the inscriptions."                                          *)
(*     - Paymaster William Thomson, USS Mohican, 1886                         *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
