(******************************************************************************)
(*                                                                            *)
(*                    Rongorongo Script Structural Properties                 *)
(*                                                                            *)
(*     Formalization of the undeciphered Rapa Nui script: reverse             *)
(*     boustrophedon reading direction (bottom-left start, 180° rotation      *)
(*     per line), Barthel glyph catalog (001–600, ~120 core signs),           *)
(*     ligature composition rules, section-marker recurrence (380.1.3),       *)
(*     and Mamari lunar calendar structure (~28-night cycle). Proves          *)
(*     reading-order determinism and parallel-text alignment decidability.    *)
(*                                                                            *)
(*     "If Rongorongo predates the arrival of external travelers, it          *)
(*      could represent another, and the latest, invention of writing         *)
(*      in human history."                                                    *)
(*     — Ferrara et al., Scientific Reports, 2024                             *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 14, 2026                                                 *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
